name = "bbplayer-backend"
main = "src/index.ts"
compatibility_date = "2025-02-01"
compatibility_flags = ["nodejs_compat"]
routes = [{ pattern = "be.bbplayer.roitium.com", custom_domain = true }]

# JWT_SECRET 和 DATABASE_URL 通过 `wrangler secret put` 设置

[dev]
local_protocol = "http"

[observability]
[observability.logs]
enabled = true
invocation_logs = true
